---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${project.artifactId}
    namespace: citrus
    labels:
      app: ${project.artifactId}
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: 'https://github.com/citrusframework/${project.artifactId}.git'
        ref: master
      sourceSecret:
        name: gitlab-ssh
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: ${project.artifactId}/src/main/docker/Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: '${project.artifactId}:latest'
    resources: {}
    postCommit: {}
    nodeSelector: null
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      fabric8.io/scm-tag: HEAD
    labels:
      expose: "true"
      app: ${project.artifactId}
      provider: fabric8
      project: ${project.artifactId}
      version: ${project.version}
      group: com.consol
    name: ${project.artifactId}-service
    namespace: citrus
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      project: ${project.artifactId}
      provider: fabric8
      group: com.consol
    type: NodePort
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-branch: master
      fabric8.io/scm-tag: HEAD
    labels:
      app: ${project.artifactId}
      provider: fabric8
      project: ${project.artifactId}
      version: ${project.version}
      group: com.consol
    name: ${project.artifactId}
    namespace: citrus
  spec:
    replicas: 1
    selector:
      project: ${project.artifactId}
      provider: fabric8
      version: ${project.version}
      group: com.consol
    template:
      metadata:
        annotations:
          fabric8.io/git-branch: master
          fabric8.io/scm-tag: HEAD
        labels:
          app: ${project.artifactId}
          provider: fabric8
          project: ${project.artifactId}
          version: ${project.version}
          group: com.consol
        namespace: citrus
      spec:
        containers:
        - env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JAVA_APP_DIR
            value: /deployments
          image: ${project.artifactId}:${project.version}
          imagePullPolicy: IfNotPresent
          name: ${project.artifactId}
          livenessProbe:
            httpGet:
              path: /todolist
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /dashboard
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 140
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
          volumeMounts:
          - name: tomcat-logs
            mountPath: /opt/tomcat/logs
          - name: tomcat-work
            mountPath: /opt/tomcat/work
          - name: tomcat-temp
            mountPath: /opt/tomcat/temp
        - env:
          - name: JAVA_APP_DIR
            value: /deployments
          image: ${project.artifactId}:${project.version}
          imagePullPolicy: IfNotPresent
          name: ${project.artifactId}
        volumes:
        - name: tomcat-logs
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-temp
          emptyDir: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${project.artifactId}
        from:
          kind: ImageStreamTag
          name: ${project.artifactId}:${project.version}
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      provider: fabric8
      project: ${project.artifactId}
      version: ${project.version}
      group: com.consol
    name: ${project.artifactId}-service
    namespace: citrus
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${project.artifactId}-service
